### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by simoncozens** [simoncozens/fontpainter#1]
- [ ] Rotations, simple and around point
- [ ] Parsing existing COLR/CPAL into our internal representation
- [x] Save/load paints inside the font in our format
- [x] Disable layer
- [x] Fix pan/zoom instability
- [x] Variable gradient opacity
- [ ] Radial/sweep gradients
  - [ ] Edit radii
- [ ] Better editing in the variation panel
- [x] Consider splitting out context provider to reduce re-renders
- [x] Undo
- [ ] Rearrange layers **This has stopped working**
- [ ] Improve VarStore optimization
- [x] **Paints have become shared between all glyphs!!!**
- [x] Bad UX: drop a font, nothing happens (On font drop, glyphs panel should open; on first edit, a new Self layer should be added.)
- [x] Layers should be renamed to Paints
- [x] <Self> should be renamed. <Current Glyph>?
- [x] Layers fold should be always open
- [ ] Center letter better, so extrema of gradient is shown
- [ ] Dump to paintcompiler
- [x] On new layer, create with same matrix as previous
- [ ] Make variation panel editable
- [x] Make little dots in axes panel bigger
- [x] White dots bigger in radial gradient editor
- [x] Make one circle of radial gradient bigger, encompassing glyph by default
- [ ] Make undo more obvious - next to canvas
- [ ]
